engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - Gemfile.lock
    - "**.erb"
    - "**.rb"
exclude_paths:
  - coverage/
  - spec/
  - Gemfile
  # git ls-files | awk '/^\./ { print "  - " $0 }'
  - .codeclimate.yml
  - .gitignore
  - .rspec
  - .ruby-version
