development:
  adapter: mysql2
  username: root
  database: tomqueue_dev
  host: 127.0.0.1
  strict: false

test:
  adapter: mysql2
  username: root
  database: tomqueue_test
  host: 127.0.0.1
  strict: false
  pool: 10
