source "https://rubygems.org"

gem "sinatra"
gem "tom_queue", path: "../"
gem "shotgun"
gem "puma"
gem "rake"
gem "pry-byebug"
gem "activesupport"
gem "rest-client"

gem "foreman"

# Specify production versions of gems
gem "mysql2"
gem 'activerecord'

gem "rspec"
gem "rspec-wait"
gem "progress_bar"
