source "https://rubygems.org"

gem "sinatra"
gem "tom_queue", path: "../"
gem "shotgun"
gem "puma"
gem "rake"
gem "pry-byebug"
gem "activesupport"
gem "activerecord"
gem "rest-client"
gem "nokogiri", "1.6.8"

gem "foreman"

# Specify production versions of gems
gem "mysql2", "0.3.21"

gem "rspec"
gem "rspec-wait"
gem "progress_bar"
