require "mysql2"
require "yaml"
load 'tom_queue/tasks.rb'

task :environment do
  require File.expand_path("../config/boot", __FILE__)
end

namespace :db do
  task :setup => :environment do
    settings = YAML.load_file(File.expand_path("../config/database.yml", __FILE__))[APP_ENV]
    client = Mysql2::Client.new(host: settings["host"], username: settings["username"], password: settings["password"])
    client.query("DROP DATABASE IF EXISTS #{settings["database"]}")
    client.query("CREATE DATABASE #{settings["database"]}")
    client.query("USE #{settings["database"]}")

    ActiveRecord::Schema.define do
      create_table :delayed_jobs, :force => true do |table|
        table.integer  :priority, :default => 0
        table.integer  :attempts, :default => 0
        table.text     :handler
        table.text     :last_error
        table.datetime :run_at
        table.datetime :locked_at
        table.datetime :failed_at
        table.string   :locked_by
        table.string   :queue
        table.timestamps null: false
      end

      add_index :delayed_jobs, [:priority, :run_at], :name => 'delayed_jobs_priority'
    end
  end
end
