mysql:
  adapter: mysql2
  database: delayed_job_test
  username: root
  encoding: utf8
  host: 127.0.0.1

postgresql:
  adapter: postgresql
  database: delayed_job_test
  username: postgres

sqlite3:
  adapter: sqlite3
  database: "/tmp/tomqueue.sqlite3"
